// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package nl.vu.cs.simbad.lab;

import java.awt.Color;
import javax.vecmath.Color3f;
import javax.vecmath.Vector3d;
import javax.vecmath.Vector3f;
import simbad.sim.Box;

public class BoxFactory {
	
	private static BoxFactory instance = new BoxFactory();
	
	private BoxFactory(){}
	public static BoxFactory getInstance(){
		return instance;
	}
	
	public Box getBox(Environment environment, int x, int z) {
		
		Box b = new Box(new Vector3d(x, 0 , z), new Vector3f(1, 1, 1), environment);
        b.setColor(new Color3f(Color.YELLOW));
		return b;	
	}
	
};
