// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package nl.vu.cs.simbad.lab;

import javax.vecmath.Vector3d;

public class CentralStation extends Subject {
	
	private int numberOfBots;
	private int boxesToBeFound;
	private Environment environment;
	private Coordinate listOfBoxes [];
	private static CentralStation instance = new CentralStation();
	
	private CentralStation(){
		this.boxesToBeFound = UserInterface.getInstance().getNumberOfBoxes();
		this.listOfBoxes = new Coordinate[this.boxesToBeFound];
		this.environment = Environment.getInstance();
		this.numberOfBots = 1;
	}
	
	public static CentralStation getInstance() {
		return instance;
	}
	
	public void addRobot(){
		Driver d = new Driver(this);
		attach(d);
		Photographer p = new Photographer(this);
		attach(p);
		Navigator n = new Navigator(this, d, p);
		attach(n);
		String name = "Robot-" + numberOfBots;
		Robot robot = new Robot(new Vector3d(0, 0, 0), name, d ,p );
		environment.add(robot);
		this.numberOfBots++;
	}
	
	public void decreaseBoxesToBeFound(Coordinate position) {
		this.listOfBoxes[this.boxesToBeFound - 1] = position;
		this.boxesToBeFound += -1;
	}
	
	@Override
	public void setState(int state){
		super.state = state;
		if(super.state == 0){
			this.setState(1);
		}
		else if(this.state == 1){	
			if(this.boxesToBeFound > 0){
				this.setState(2);
			}
			else{
				System.out.println("END OF THE MISSION");
				for(int i = 0; i < this.listOfBoxes.length; i++){
					System.out.println(this.listOfBoxes[i].getCoords());
				}
				this.setState(6);
			}
		}
		super.notifyAllObservers();
	}
};
