// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package nl.vu.cs.simbad.lab;

import javax.vecmath.Point3d;

public class Coordinate {

	private double latidudeX;
	private double longitudeZ;

	public void setCoords(Point3d point) {
		this.latidudeX = point.x;
		this.longitudeZ = point.z;
	}

	public String getCoords() {
		String position = "{Latidude: " + Double.toString(this.latidudeX) + ", Longitude: " + Double.toString(this.longitudeZ) + "}";
		return position;
	}
};
