// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package nl.vu.cs.simbad.lab;

public class Driver extends Observer {
	
	private Double angle;
	private Robot robot;
	private CentralStation centralstation;
	
	public Driver(CentralStation cs){
		this.centralstation = cs;
	}
	
	@Override
	public void Update(){
		if(this.centralstation.getState() == 5){
			this.robot.setDriveMode(1);
			driveToGoal();
		}else if(this.centralstation.getState() == 2){
			this.robot.setDriveMode(0);
			this.robot.initBehavior();
		}else if(this.centralstation.getState() == 6){
			this.robot.setTranslationalVelocity(0);
			this.robot.detach();
		}
	}
	
	public void driveToGoal() {
		this.robot.rotateY(angle);
		this.robot.setTranslationalVelocity(0.5);
	}

	public void setAngle(double a) {
		this.angle =  a;
	}

	public void assignRobot(Robot r) {
		this.robot = r;
	}
	public void hitDetected(){
		this.robot.setDriveMode(3);
		if(this.centralstation.getState() != 6)
			  this.centralstation.setState(3);
	}
};
