// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package nl.vu.cs.simbad.lab;

import java.awt.Color;
import javax.vecmath.Color3f;
import javax.vecmath.Vector3d;
import simbad.sim.EnvironmentDescription;
import simbad.sim.Wall;

public class Environment extends EnvironmentDescription{
	
	private static Environment instance = new Environment();
	
	private Environment(){
		this.light1IsOn = true;
        this.light2IsOn = true;

        // enable the physics engine in order to have better physics effects on the objects
        this.setUsePhysics(true);

        // show the axes so that we know where things are
        this.showAxis(true);

        // Set the world size
        this.setWorldSize(25);
        this.floorColor = this.gray;
        Wall w1 = new Wall(new Vector3d(-12.5, 0, 0), 25, 2, this);
        w1.setColor(new Color3f(Color.GRAY));
        w1.rotate90(1);
        add(w1);

        Wall w2 = new Wall(new Vector3d(12.5, 0, 0), 25, 2, this);
        w2.setColor(new Color3f(Color.GRAY));
        w2.rotate90(1);
        add(w2);

        Wall w3 = new Wall(new Vector3d(0, 0, 12.5), 25, 2, this);
        w3.setColor(new Color3f(Color.GRAY));
        add(w3);

        Wall w4 = new Wall(new Vector3d(0, 0, -12.5), 25, 2, this);
        w4.setColor(new Color3f(Color.GRAY));
        add(w4);

        Wall in1 = new Wall(new Vector3d(4, 0, -1), 6, 2, this);
        in1.setColor(new Color3f(Color.GRAY));
        add(in1);

        Wall in2 = new Wall(new Vector3d(1, 0, -4), 6, 2, this);
        in2.setColor(new Color3f(Color.GRAY));
        in2.rotate90(1);
        add(in2);

        Wall t1 = new Wall(new Vector3d(-5, 0, 5), 8, 2, this);
        t1.setColor(new Color3f(Color.GRAY));
        t1.rotate90(1);
        add(t1);

        Wall t2 = new Wall(new Vector3d(-9, 0, 5), 8, 2, this);
        t2.setColor(new Color3f(Color.GRAY));
        t2.rotate90(1);
        add(t2);

        Wall smol10 = new Wall(new Vector3d(-4, 0, -4), 6, 1, this);
        smol10.setColor(new Color3f(Color.GRAY));
        add(smol10);

        Wall smol11 = new Wall(new Vector3d(-1, 0, -7), 6, 1, this);
        smol11.setColor(new Color3f(Color.GRAY));
        smol11.rotate90(1);
        add(smol11);

        Wall smol20 = new Wall(new Vector3d(4, 0, 4), 6, 1, this);
        smol20.setColor(new Color3f(Color.GRAY));
        add(smol20);

        Wall smol21 = new Wall(new Vector3d(1, 0, 7), 6, 1, this);
        smol21.setColor(new Color3f(Color.GRAY));
        smol21.rotate90(1);
        add(smol21);
	}
	
	public static Environment getInstance() {
		return instance;
	}
};
