// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package nl.vu.cs.simbad.lab;


public abstract class Observer {
	
	public void Update(){}
};
