// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package nl.vu.cs.simbad.lab;

import java.awt.image.BufferedImage;
import java.util.ArrayList;
import java.util.concurrent.TimeUnit;


public class Photographer extends Observer {
	
	private int bestPhoto;
	private Robot robot;
	private CentralStation centralstation;
	
	public Photographer(CentralStation cs){
		this.centralstation = cs;
	}
	
	public int getBestPhoto(){
		return this.bestPhoto;
	}
	
	@Override
	public void Update(){
		if(this.centralstation.getState() == 3){
			try{
				takePhotos();
			}catch(InterruptedException ex)
			{
			    Thread.currentThread().interrupt();
			}
		}else{}
	}
	
	public void takePhotos() throws InterruptedException {
		double ratio = 0;
		ArrayList<BufferedImage> images = this.robot.takePhotos();
		for(int i = 0; i < 10;i++){
			double good = 0;
			double bad = 0;
			ArrayList<Integer>pixels = new ArrayList<Integer>();
			for (int row = 0; row < 100; row++) {
				for (int col = 0; col < 100; col++) {
					pixels.add(images.get(i).getRGB(col, row));
				}
			}
			for (int pixel : pixels){
				 int b = (pixel)&0xFF;
				 int g = (pixel>>8)&0xFF;
				 int r = (pixel>>16)&0xFF;
				 if(r > 100 && g > 100 && b < 130){
					 good++;
				 }else{
					 bad++;
				 }
			}
			//System.out.println("g" + good + "b" + bad);
			if(bad < 1){
				ratio = 1;
				this.bestPhoto = i + 1;
			}
			else if(ratio < (good/10000)){
				ratio = good/10000;
				this.bestPhoto = i + 1;
			}	
		}
		//System.out.println("NAJLEPSZE FOTO " + this.bestPhoto);
		if(ratio > 0.45){
			Coordinate cord = new Coordinate();
			cord.setCoords(this.robot.getPosition());
			this.centralstation.decreaseBoxesToBeFound(cord);
			this.centralstation.setState(1);
		}else if(this.bestPhoto != 0){
			if(this.centralstation.getState() != 6)
				this.centralstation.setState(4);
		}else{
			if(this.centralstation.getState() != 6)
				this.centralstation.setState(2);
		}
	}

	public void assignRobot(Robot r) {
		this.robot = r;
	}
};
