// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package nl.vu.cs.simbad.lab;

import java.util.ArrayList;
import java.util.List;

public abstract class Subject {
	
	private List<Observer> observers = new ArrayList<Observer>();
	public int state;

	public int getState() {
		return this.state;
	}

	public void setState(int state) {
		this.state = state;
		this.notifyAllObservers();
	}

	public void attach(Observer observer) {
		this.observers.add(observer);
	}

	public void notifyAllObservers() {
		for (Observer observer : this.observers) {
			observer.Update();
	 }
	}
};
