// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package nl.vu.cs.simbad.lab;

import java.util.Scanner;

import simbad.sim.Box;

public class UserInterface {
	
	private int numberOfBoxes;
	private BoxFactory boxFactory;
	private Environment environment;
	private static UserInterface instance = new UserInterface();
	
	private UserInterface(){}
	
	public static UserInterface getInstance(){
		return instance;
	}
	
	public void addBoxes(Environment e) {
		this.boxFactory = BoxFactory.getInstance();
		this.environment = e;
		System.out.println("How many boxes do you want to add?");
		try{
			Scanner input = new Scanner(System.in);
			this.numberOfBoxes = input.nextInt();
			if(this.numberOfBoxes < 1){
				throw new Exception();
			}
			for (int i = 0; i < this.numberOfBoxes; i++) {
				System.out.println("Give x coordinates");
				int x = input.nextInt();
				if(x < 1){
					throw new Exception();
				}
				System.out.println("Give z coordinates");
				int z = input.nextInt();
				if(z < 1){
					throw new Exception();
				}
				Box b = boxFactory.getBox(environment, x, z);
				environment.add(b);
			}
			input.close();
		}catch(Exception exception){
			System.out.println("Invalid input. Aborting mission");
			System.exit(0);
		}
	    
	}
	
	public int getNumberOfBoxes(){
		return this.numberOfBoxes;
	}
};
